from __future__ import annotations

from dataclasses import asdict

import torch
from torch import nn
from torch.utils.data import DataLoader

from parameters import AttackConfig, DataConfig


def _get_mean_std_tensors(
    data_config: DataConfig,
    device: torch.device,
) -> tuple[torch.Tensor, torch.Tensor]:
    mean = torch.tensor(data_config.mean, device=device).view(1, 3, 1, 1)
    std = torch.tensor(data_config.std, device=device).view(1, 3, 1, 1)
    return mean, std


def denormalize_images(
    images: torch.Tensor,
    data_config: DataConfig,
    device: torch.device,
) -> torch.Tensor:
    mean, std = _get_mean_std_tensors(data_config, device)
    return images * std + mean


def normalize_images(
    images: torch.Tensor,
    data_config: DataConfig,
    device: torch.device,
) -> torch.Tensor:
    mean, std = _get_mean_std_tensors(data_config, device)
    return (images - mean) / std


def _project_l2(delta: torch.Tensor, epsilon: float) -> torch.Tensor:
    flat_delta = delta.view(delta.size(0), -1)
    norms = torch.norm(flat_delta, p=2, dim=1, keepdim=True).clamp(min=1e-12)
    factors = torch.clamp(epsilon / norms, max=1.0)
    projected = flat_delta * factors
    return projected.view_as(delta)


def _random_l2_delta_like(
    images: torch.Tensor,
    epsilon: float,
) -> torch.Tensor:
    delta = torch.randn_like(images)
    flat_delta = delta.view(delta.size(0), -1)
    norms = torch.norm(flat_delta, p=2, dim=1, keepdim=True).clamp(min=1e-12)
    directions = flat_delta / norms

    radii = torch.rand(images.size(0), 1, device=images.device)
    scaled = directions * (radii * epsilon)

    return scaled.view_as(images)


def pgd_attack(
    model: nn.Module,
    images_norm: torch.Tensor,
    labels: torch.Tensor,
    attack_config: AttackConfig,
    data_config: DataConfig,
    device: torch.device,
) -> torch.Tensor:
    """
    Generate PGD adversarial examples in pixel space [0, 1],
    then return them normalized for model inference.
    """
    model.eval()
    criterion = nn.CrossEntropyLoss()

    images = denormalize_images(images_norm, data_config, device).clamp(0.0, 1.0)
    adv = images.clone().detach()

    if attack_config.random_start:
        if attack_config.norm == "linf":
            adv = adv + torch.empty_like(adv).uniform_(
                -attack_config.epsilon,
                attack_config.epsilon,
            )
        else:
            adv = adv + _random_l2_delta_like(adv, attack_config.epsilon)

        adv = adv.clamp(0.0, 1.0)

    for _ in range(attack_config.steps):
        adv.requires_grad_(True)

        model.zero_grad(set_to_none=True)

        adv_norm = normalize_images(adv, data_config, device)
        logits = model(adv_norm)
        loss = criterion(logits, labels)

        grad = torch.autograd.grad(loss, adv)[0]

        if attack_config.norm == "linf":
            adv = adv.detach() + attack_config.step_size * grad.sign()
            delta = torch.clamp(
                adv - images,
                min=-attack_config.epsilon,
                max=attack_config.epsilon,
            )
        else:
            grad_flat = grad.view(grad.size(0), -1)
            grad_norm = torch.norm(grad_flat, p=2, dim=1, keepdim=True).clamp(min=1e-12)
            normalized_grad = grad_flat / grad_norm
            normalized_grad = normalized_grad.view_as(grad)

            adv = adv.detach() + attack_config.step_size * normalized_grad
            delta = adv - images
            delta = _project_l2(delta, attack_config.epsilon)

        adv = torch.clamp(images + delta, min=0.0, max=1.0).detach()

    adv_norm = normalize_images(adv, data_config, device)
    return adv_norm


def evaluate_under_pgd(
    model: nn.Module,
    dataloader: DataLoader,
    attack_config: AttackConfig,
    data_config: DataConfig,
    device: torch.device,
    max_samples: int | None = None,
) -> dict[str, float | int | dict]:
    """
    Evaluate a model on clean and adversarial samples generated by PGD.
    """
    model.eval()
    criterion = nn.CrossEntropyLoss()

    clean_loss_sum = 0.0
    adv_loss_sum = 0.0

    clean_correct = 0
    adv_correct = 0
    total = 0

    attack_success_on_clean = 0
    clean_correct_total = 0

    for images, labels in dataloader:
        if max_samples is not None and total >= max_samples:
            break

        if max_samples is not None:
            remaining = max_samples - total
            if remaining <= 0:
                break
            images = images[:remaining]
            labels = labels[:remaining]

        images = images.to(device)
        labels = labels.to(device)

        with torch.no_grad():
            clean_logits = model(images)
            clean_loss = criterion(clean_logits, labels)
            clean_preds = clean_logits.argmax(dim=1)

        adv_images = pgd_attack(
            model=model,
            images_norm=images,
            labels=labels,
            attack_config=attack_config,
            data_config=data_config,
            device=device,
        )

        with torch.no_grad():
            adv_logits = model(adv_images)
            adv_loss = criterion(adv_logits, labels)
            adv_preds = adv_logits.argmax(dim=1)

        batch_size = labels.size(0)

        clean_loss_sum += clean_loss.item() * batch_size
        adv_loss_sum += adv_loss.item() * batch_size

        clean_correct += (clean_preds == labels).sum().item()
        adv_correct += (adv_preds == labels).sum().item()

        clean_mask = clean_preds == labels
        clean_correct_total += clean_mask.sum().item()
        attack_success_on_clean += ((adv_preds != labels) & clean_mask).sum().item()

        total += batch_size

    clean_accuracy = 100.0 * clean_correct / total if total > 0 else 0.0
    adv_accuracy = 100.0 * adv_correct / total if total > 0 else 0.0
    clean_loss_avg = clean_loss_sum / total if total > 0 else 0.0
    adv_loss_avg = adv_loss_sum / total if total > 0 else 0.0

    if clean_correct_total > 0:
        attack_success_rate = 100.0 * attack_success_on_clean / clean_correct_total
    else:
        attack_success_rate = 0.0

    return {
        "num_samples": total,
        "attack": asdict(attack_config),
        "clean_loss": clean_loss_avg,
        "clean_accuracy": clean_accuracy,
        "adv_loss": adv_loss_avg,
        "adv_accuracy": adv_accuracy,
        "attack_success_rate_on_clean": attack_success_rate,
    }


def evaluate_transfer_attack(
    teacher_model: nn.Module,
    student_model: nn.Module,
    dataloader: DataLoader,
    attack_config: AttackConfig,
    data_config: DataConfig,
    device: torch.device,
    max_samples: int | None = None,
) -> dict[str, float | int | dict]:
    """
    Generate adversarial examples using the teacher model and evaluate both
    teacher and student on those same adversarial examples.
    """
    teacher_model.eval()
    student_model.eval()

    criterion = nn.CrossEntropyLoss()

    teacher_clean_loss_sum = 0.0
    teacher_adv_loss_sum = 0.0
    student_clean_loss_sum = 0.0
    student_adv_loss_sum = 0.0

    teacher_clean_correct = 0
    teacher_adv_correct = 0
    student_clean_correct = 0
    student_adv_correct = 0

    teacher_attack_success_on_clean = 0
    teacher_clean_correct_total = 0

    transfer_success_on_student_clean = 0
    student_clean_correct_total = 0

    total = 0

    for images, labels in dataloader:
        if max_samples is not None and total >= max_samples:
            break

        if max_samples is not None:
            remaining = max_samples - total
            if remaining <= 0:
                break
            images = images[:remaining]
            labels = labels[:remaining]

        images = images.to(device)
        labels = labels.to(device)

        with torch.no_grad():
            teacher_clean_logits = teacher_model(images)
            teacher_clean_loss = criterion(teacher_clean_logits, labels)
            teacher_clean_preds = teacher_clean_logits.argmax(dim=1)

            student_clean_logits = student_model(images)
            student_clean_loss = criterion(student_clean_logits, labels)
            student_clean_preds = student_clean_logits.argmax(dim=1)

        adv_images = pgd_attack(
            model=teacher_model,
            images_norm=images,
            labels=labels,
            attack_config=attack_config,
            data_config=data_config,
            device=device,
        )

        with torch.no_grad():
            teacher_adv_logits = teacher_model(adv_images)
            teacher_adv_loss = criterion(teacher_adv_logits, labels)
            teacher_adv_preds = teacher_adv_logits.argmax(dim=1)

            student_adv_logits = student_model(adv_images)
            student_adv_loss = criterion(student_adv_logits, labels)
            student_adv_preds = student_adv_logits.argmax(dim=1)

        batch_size = labels.size(0)

        teacher_clean_loss_sum += teacher_clean_loss.item() * batch_size
        teacher_adv_loss_sum += teacher_adv_loss.item() * batch_size
        student_clean_loss_sum += student_clean_loss.item() * batch_size
        student_adv_loss_sum += student_adv_loss.item() * batch_size

        teacher_clean_correct += (teacher_clean_preds == labels).sum().item()
        teacher_adv_correct += (teacher_adv_preds == labels).sum().item()
        student_clean_correct += (student_clean_preds == labels).sum().item()
        student_adv_correct += (student_adv_preds == labels).sum().item()

        teacher_clean_mask = teacher_clean_preds == labels
        teacher_clean_correct_total += teacher_clean_mask.sum().item()
        teacher_attack_success_on_clean += (
            (teacher_adv_preds != labels) & teacher_clean_mask
        ).sum().item()

        student_clean_mask = student_clean_preds == labels
        student_clean_correct_total += student_clean_mask.sum().item()
        transfer_success_on_student_clean += (
            (student_adv_preds != labels) & student_clean_mask
        ).sum().item()

        total += batch_size

    teacher_clean_accuracy = 100.0 * teacher_clean_correct / total if total > 0 else 0.0
    teacher_adv_accuracy = 100.0 * teacher_adv_correct / total if total > 0 else 0.0
    student_clean_accuracy = 100.0 * student_clean_correct / total if total > 0 else 0.0
    student_adv_accuracy = 100.0 * student_adv_correct / total if total > 0 else 0.0

    teacher_clean_loss_avg = teacher_clean_loss_sum / total if total > 0 else 0.0
    teacher_adv_loss_avg = teacher_adv_loss_sum / total if total > 0 else 0.0
    student_clean_loss_avg = student_clean_loss_sum / total if total > 0 else 0.0
    student_adv_loss_avg = student_adv_loss_sum / total if total > 0 else 0.0

    if teacher_clean_correct_total > 0:
        teacher_attack_success_rate = (
            100.0 * teacher_attack_success_on_clean / teacher_clean_correct_total
        )
    else:
        teacher_attack_success_rate = 0.0

    if student_clean_correct_total > 0:
        transfer_success_rate = (
            100.0 * transfer_success_on_student_clean / student_clean_correct_total
        )
    else:
        transfer_success_rate = 0.0

    return {
        "num_samples": total,
        "attack": asdict(attack_config),
        "teacher_clean_loss": teacher_clean_loss_avg,
        "teacher_clean_accuracy": teacher_clean_accuracy,
        "teacher_adv_loss": teacher_adv_loss_avg,
        "teacher_adv_accuracy": teacher_adv_accuracy,
        "teacher_attack_success_rate_on_clean": teacher_attack_success_rate,
        "student_clean_loss": student_clean_loss_avg,
        "student_clean_accuracy": student_clean_accuracy,
        "student_adv_loss": student_adv_loss_avg,
        "student_adv_accuracy": student_adv_accuracy,
        "transfer_success_rate_on_student_clean": transfer_success_rate,
    }