
import json
import os

from dataset import DEFAULT_HORIZONS

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "results")
MODELS = ["lstm", "gru"]
TARGETS = ["exact", "rolling"]


def load(name):
    path = os.path.join(RESULTS_DIR, name)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def fmt(x, p=6):
    return f"{x:.{p}e}" if x else f"{x:.{p}e}"


def regression_section(lines):
    lines.append("## Exact vs rolling-average forecasting (Parts 1b/1c)\n")
    lines.append("Overall MSE / MAE per split (lower is better):\n")
    lines.append("| model | target | train MSE | val MSE | test MSE | test MAE |")
    lines.append("|---|---|---|---|---|---|")
    for m in MODELS:
        for t in TARGETS:
            mx = load(f"{m}_{t}_metrics.json")
            if not mx:
                continue
            lines.append(f"| {m} | {t} | {fmt(mx['train']['mse'])} | "
                         f"{fmt(mx['val']['mse'])} | {fmt(mx['test']['mse'])} | "
                         f"{fmt(mx['test']['mae'])} |")
    lines.append("")

    lines.append("Per-horizon test MSE:\n")
    head = "| model | target | " + " | ".join(f"d={d}" for d in DEFAULT_HORIZONS) + " |"
    lines.append(head)
    lines.append("|---|---|" + "---|" * len(DEFAULT_HORIZONS))
    for m in MODELS:
        for t in TARGETS:
            mx = load(f"{m}_{t}_metrics.json")
            if not mx:
                continue
            ph = mx["test"]["per_horizon_mse"]
            cells = " | ".join(fmt(ph[f"d={d}"]) for d in DEFAULT_HORIZONS)
            lines.append(f"| {m} | {t} | {cells} |")
    lines.append("")

    comp = load("comparison_summary.json")
    if comp:
        lines.append("Training stability (validation curve smoothness; "
                     "lower = more stable):\n")
        lines.append("| run | best val MSE | val std (2nd half) | val jitter |")
        lines.append("|---|---|---|---|")
        for tag, s in comp.items():
            lines.append(f"| {tag} | {fmt(s['best_val_mse'])} | "
                         f"{fmt(s['val_std_second_half'])} | "
                         f"{fmt(s['val_jitter_mean_abs_step'])} |")
        lines.append("")


def turning_section(lines):
    lines.append("## Turning-point detection (Part 1d)\n")
    lines.append("Bidirectional LSTM/GRU, buy if any max-price d-day return "
                 "exceeds gamma.\n")

    # Class balance (same for both rnns; read from a train log).
    log = load("turning_lstm_train_log.json")
    if log and "class_balance" in log:
        cb = log["class_balance"]
        lines.append("**Class balance at the official gamma=1.1** "
                     "(buy / total):\n")
        lines.append("| split | buy | total | buy rate |")
        lines.append("|---|---|---|---|")
        for s in ("train", "val", "test"):
            b = cb[s]
            lines.append(f"| {s} | {b['buy']} | {b['n']} | {b['buy_rate']:.4%} |")
        lines.append("")

    def metrics_row(tag, label):
        mx = load(f"{tag}_metrics.json")
        if not mx:
            return None
        t = mx["splits"]["test"]
        cm = t["confusion_matrix"]
        return (f"| {label} | {mx['gamma']:g} | {t['accuracy']:.4f} | "
                f"{t['precision']:.4f} | {t['recall']:.4f} | {t['f1']:.4f} | "
                f"{cm['tp']}/{cm['fp']}/{cm['fn']}/{cm['tn']} |")

    lines.append("Test-set metrics (official gamma=1.1 = required result; "
                 "gamma=0.05 = supplementary sanity check):\n")
    lines.append("| run | gamma | accuracy | precision | recall | F1 | "
                 "TP/FP/FN/TN |")
    lines.append("|---|---|---|---|---|---|---|")
    for m in MODELS:
        row = metrics_row(f"turning_{m}", f"{m} (official)")
        if row:
            lines.append(row)
    for m in MODELS:
        row = metrics_row(f"turning_{m}_g0.05", f"{m} (suppl.)")
        if row:
            lines.append(row)
    lines.append("")
    lines.append("> At gamma=1.1 the buy class is empty in every split, so the "
                 "model trivially predicts 'pass' everywhere and reaches "
                 "100% accuracy with precision/recall/F1 = 0. This is a "
                 "property of the threshold (a >110% gain in 5 days never "
                 "occurs for these tickers), not a modelling success.\n")


def main():
    lines = ["# Part 1 — Final Results Summary\n",
             "Auto-generated by `summarize.py` from the JSON artifacts in "
             "`results/`. Tickers: AAPL, MSFT, JPM. Lookback T=20, horizons "
             "d=1..5. Splits: train 2020-01..2024-07, val 2024-08..2024-12, "
             "test 2025-01..2025-12.\n"]
    regression_section(lines)
    turning_section(lines)
    out = os.path.join(RESULTS_DIR, "PART1_SUMMARY.md")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
